name: Безопасность

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security:
    runs-on: ubuntu-latest
    
    steps:
    - name: Код
      uses: actions/checkout@v4
      
    - name: Права
      run: chmod +x ./gradlew
      
    - name: Java
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
          
    - name: SpotBugs
      run: ./gradlew spotbugsMain
      continue-on-error: true
      
    - name: Snyk
      uses: snyk/actions/gradle@master
      continue-on-error: true
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        
    - name: Сборка
      run: ./gradlew build
